# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_KEY: ${{ secrets.CONTENTFUL_ACCESS_KEY }}
      CONTENTFUL_WEBHOOK_TOKEN: ${{ secrets.CONTENTFUL_WEBHOOK_TOKEN }}
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Debug Environment Variables
      run: |
        echo "CONTENTFUL_ACCESS_KEY=${{ secrets.CONTENTFUL_ACCESS_KEY }}"
        echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}"
    - run: npm run build --if-present
    - name: Change Directory
      run: cd /home/apurva/actions-runner/_work/archiive/archiive
    - run: pm2 restart 0
